[build]
  base = "jekyll"
  publish = "../docs"

  # Set the baseurl to "/" and url to "$DEPLOY_PRIME_URL" so that the built site is served from the root
  command = """
  printf "url: \"$DEPLOY_PRIME_URL\"\nbaseurl: \"/\"" > _config_netlify.yml; \
  bundle exec jekyll build --config _config.yml,_config_netlify.yml \
  """

  # Only build if netlify.toml or jekyll files have changed
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF netlify.toml jekyll"
